database:
  type: postgres
  host: localhost
  port: 5432
  username: exix
  password: exix2025
  database: exix_db
  entities:
    - "**/entity/*{.ts,.js}"
    - "src/**/*.entity{.ts,.js}"
  synchronize: false

redis:
  port: 6379
  host: localhost
  password: exix2025
  db: 2

# 其他开发环境配置可以放在这里
server:
  port: 6020
  url: http://127.0.0.1:6020
  language: en
    