name: CI for Fronted and Backend 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-fronted-with-nextjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9 
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Run Next.js setup script
        run: bash ./.github/scripts/frontend-setup.sh

  build-backend-with-nestjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9 
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Run Nest.js setup script
        run: bash ./.github/scripts/backend-setup.sh
